matrix:
  include:
    - language: rust
      rust:
        - stable
      jobs:
        allow_failures:
          - rust: nightly
        fast_finish: true    
    
    - language: node.js
      node_js: "12.0"
      before_script:
        - cd angular-application
      script:
        - npm install
        - ng build --prod